version: '2'
services:
  mysql_spgssu:
    image: mysql:8.0
    container_name: mysql_spgssu
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./MySQL:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=clave123
      - MYSQL_DATABASE=sgpssu
    ports:
      - '33062:3306'
  php_spgssu:
    container_name: php_spgssu
    build:
      context: ./
    volumes:
      - ./app:/var/www/html
    ports:
      - 82:80
    depends_on:
      - mysql_spgssu
